/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package form;

import communication.Communication;
import domain.Autobus;
import domain.Mesto;
import domain.Vozac;
import domain.Voznja;
import java.sql.Time;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class FrmIzmeniVoznju extends javax.swing.JDialog {

    /**
     * Creates new form FrmIzmeniVoznju
     */
    public FrmIzmeniVoznju(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        prepareInputs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        lblVoznja = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnIzmeni = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jdpDatumPolaska = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        tbHours = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tbMinutes = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tbSecundes = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbVozac = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cbAutobus = new javax.swing.JComboBox<>();
        lblNoviDatum = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tbDatum = new javax.swing.JTextField();
        tbVreme = new javax.swing.JTextField();
        tbVozac = new javax.swing.JTextField();
        tbMestoDolaska = new javax.swing.JTextField();
        tbAutobus = new javax.swing.JTextField();
        cbVoznje = new javax.swing.JComboBox<>();

        jTextField5.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblVoznja.setBorder(javax.swing.BorderFactory.createTitledBorder("Izmeni voznju"));

        jLabel1.setText("Izaberi Voznju");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Datum polaska");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Vreme polaska (hh:mm:ss)");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Autobus");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Mesto dolaska");

        btnIzmeni.setText("Izmeni voznju");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NOVI PODACI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 51, 255))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Vreme polaska (hh:mm:ss)");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText(":");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText(":");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Vozac");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Autobus");

        lblNoviDatum.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNoviDatum.setText("Datum polaska");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNoviDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(jdpDatumPolaska, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tbHours, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(tbMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(tbSecundes, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbAutobus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbVozac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdpDatumPolaska, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNoviDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tbHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tbMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(tbSecundes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbVozac, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbAutobus, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 52, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Vozac");

        tbDatum.setEnabled(false);
        tbDatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbDatumActionPerformed(evt);
            }
        });

        tbVreme.setEnabled(false);
        tbVreme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbVremeActionPerformed(evt);
            }
        });

        tbVozac.setEnabled(false);

        tbMestoDolaska.setEnabled(false);

        tbAutobus.setEnabled(false);

        cbVoznje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVoznjeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lblVoznjaLayout = new javax.swing.GroupLayout(lblVoznja);
        lblVoznja.setLayout(lblVoznjaLayout);
        lblVoznjaLayout.setHorizontalGroup(
            lblVoznjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblVoznjaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(lblVoznjaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lblVoznjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblVoznjaLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(tbDatum))
                    .addGroup(lblVoznjaLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbVoznje, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(lblVoznjaLayout.createSequentialGroup()
                        .addGroup(lblVoznjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(lblVoznjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbVreme)
                            .addComponent(tbVozac)
                            .addComponent(tbMestoDolaska, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tbAutobus, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        lblVoznjaLayout.setVerticalGroup(
            lblVoznjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblVoznjaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(lblVoznjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(cbVoznje, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lblVoznjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lblVoznjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tbVreme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(lblVoznjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tbVozac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lblVoznjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tbAutobus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lblVoznjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tbMestoDolaska, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIzmeni)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVoznja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVoznja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbDatumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbDatumActionPerformed

    private void tbVremeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbVremeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbVremeActionPerformed

    private void cbVoznjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVoznjeActionPerformed
        Voznja voznja=(Voznja)cbVoznje.getSelectedItem();
        tbAutobus.setText(voznja.getAutobus().toString());
        tbDatum.setText(voznja.getDatumPolaska().toString());
        tbVreme.setText(voznja.getVremePolaska().toString());
        tbVozac.setText(voznja.getVozac().toString());
        
        try {
            Mesto mesto = Communication.getInstance().getMestoZaZadatuVoznju(voznja);
            tbMestoDolaska.setText(mesto.getNaziv());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_cbVoznjeActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
            
        validateInputs();
        int hours   = Integer.parseInt(tbHours.getText()); 
        int minutes = Integer.parseInt(tbMinutes.getText()); 
        int secunds = Integer.parseInt(tbSecundes.getText()); 
        Voznja voznja = (Voznja)cbVoznje.getSelectedItem();
        Time time=new Time(hours, minutes, secunds);
        voznja.setVozac((Vozac)cbVozac.getSelectedItem());
        voznja.setDatumPolaska((Date)jdpDatumPolaska.getDate());
        voznja.setAutobus((Autobus)cbAutobus.getSelectedItem());
        voznja.setVremePolaska(time);
        try {

             Communication.getInstance().zapamtiVoznju(voznja);
             

        } catch (Exception ex) {
            Logger.getLogger(FrmVoznja.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JComboBox<Object> cbAutobus;
    private javax.swing.JComboBox<Object> cbVozac;
    private javax.swing.JComboBox<Object> cbVoznje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField5;
    private com.toedter.calendar.JDateChooser jdpDatumPolaska;
    private javax.swing.JLabel lblNoviDatum;
    private javax.swing.JPanel lblVoznja;
    private javax.swing.JTextField tbAutobus;
    private javax.swing.JTextField tbDatum;
    private javax.swing.JTextField tbHours;
    private javax.swing.JTextField tbMestoDolaska;
    private javax.swing.JTextField tbMinutes;
    private javax.swing.JTextField tbSecundes;
    private javax.swing.JTextField tbVozac;
    private javax.swing.JTextField tbVreme;
    // End of variables declaration//GEN-END:variables
    private void prepareInputs() {
        try {
            List<Voznja> voznje = Communication.getInstance().ucitajListuVoznji();
            for (Voznja voznja : voznje) {
            cbVoznje.addItem(voznja);
            }
            List<Vozac> vozaci = Communication.getInstance().ucitajListuVozaca();
            for (Vozac vozac : vozaci) {
            cbVozac.addItem(vozac);
            }
            List<Autobus> autobusi = Communication.getInstance().ucitajListuAutobusa();
            for (Autobus autobus : autobusi) {
            cbAutobus.addItem(autobus);
            }
           
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    private void validateInputs() {
        String hh=tbHours.getText();
        String mm=tbMinutes.getText();
        String ss=tbSecundes.getText();
        if(jdpDatumPolaska.getDate()==null){
            JOptionPane.showMessageDialog(this, "Morate izabrati datum voznje koju unosite");
            return;
        }
         if(hh.isEmpty()||mm.isEmpty()||ss.isEmpty()){
            JOptionPane.showMessageDialog(this, "Obavezno je uneti vreme voznje");
            return;
        }
         if(cbAutobus.getSelectedItem()==null ){
             JOptionPane.showMessageDialog(this, "Obavezno je uneti autobus");
             return;
         }
         
          if(cbVozac.getSelectedItem()==null ){
             JOptionPane.showMessageDialog(this, "Obavezno je uneti vozaca za voznju");
             return;
         }
        try {
            int hours   = Integer.parseInt(hh); 
            int minutes = Integer.parseInt(mm); 
            int secunds = Integer.parseInt(ss); 
            
            if(hours>24||hours<0||minutes<0||minutes>60||secunds>60||secunds<0){
             JOptionPane.showMessageDialog(this, "Vreme mora biti u validnom formatu HH:[0-24], MM:[0-60], SS:[0-60]");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vreme mora biti u validnom formatu HH:[0-24], MM:[0-60], SS:[0-60]");
        }
    }
}
