/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package form;

import communication.Communication;
import domain.Autobus;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class FrmIzmeniAutobus extends javax.swing.JDialog {

    /**
     * Creates new form FrmIzmeniAutobus
     */
    public FrmIzmeniAutobus(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        prepareIzmena();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRegBroj = new javax.swing.JLabel();
        lblRegBroj1 = new javax.swing.JLabel();
        lblMarka = new javax.swing.JLabel();
        lblGodinaProzivodnje = new javax.swing.JLabel();
        lblBrMesta = new javax.swing.JLabel();
        lblVrsta = new javax.swing.JLabel();
        tbRegBroj = new javax.swing.JTextField();
        tbMarka = new javax.swing.JTextField();
        tbGodProizvodnje = new javax.swing.JTextField();
        tbBrojMesta = new javax.swing.JTextField();
        btnIzmeni = new javax.swing.JToggleButton();
        tbVrsta = new javax.swing.JTextField();
        jcbAutobusi = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("IZMENI AUTOBUS"));

        lblRegBroj.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRegBroj.setText("Izaberi autobus");

        lblRegBroj1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRegBroj1.setText("Registarski broj");

        lblMarka.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMarka.setText("Marka");

        lblGodinaProzivodnje.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGodinaProzivodnje.setText("Godina proizvodnje");

        lblBrMesta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBrMesta.setText("Broj mesta");

        lblVrsta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblVrsta.setText("Vrsta ");

        tbRegBroj.setEnabled(false);
        tbRegBroj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbRegBrojActionPerformed(evt);
            }
        });

        tbMarka.setEnabled(false);

        tbGodProizvodnje.setEnabled(false);

        tbBrojMesta.setEnabled(false);

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        tbVrsta.setEnabled(false);

        jcbAutobusi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbAutobusiMouseClicked(evt);
            }
        });
        jcbAutobusi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAutobusiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGodinaProzivodnje, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblRegBroj, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(84, 84, 84)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcbAutobusi, 0, 182, Short.MAX_VALUE)
                                    .addComponent(tbGodProizvodnje)
                                    .addComponent(tbRegBroj)
                                    .addComponent(tbMarka)
                                    .addComponent(tbBrojMesta)
                                    .addComponent(tbVrsta))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMarka, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBrMesta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVrsta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRegBroj1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(426, 426, 426))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRegBroj)
                    .addComponent(jcbAutobusi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegBroj1)
                    .addComponent(tbRegBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarka)
                    .addComponent(tbMarka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGodinaProzivodnje)
                    .addComponent(tbGodProizvodnje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBrMesta)
                    .addComponent(tbBrojMesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVrsta)
                    .addComponent(tbVrsta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
         if(jcbAutobusi.getSelectedItem()==null){
            JOptionPane.showMessageDialog(this,"Morate izabrati autobus!");
            return;
        }
        
        String brojSedista = tbBrojMesta.getText();
        int brojMesta=0;
        if(brojSedista.length()==0){
            JOptionPane.showMessageDialog(this,"Broj mesta autobusa je obavezan!");
            return;
        }
        try {
            brojMesta = Integer.parseInt(brojSedista);
            Autobus autobus = (Autobus)jcbAutobusi.getSelectedItem();
            autobus.setBrojMesta(brojMesta);
            Communication.getInstance().zapamtiAutobus(autobus);
            JOptionPane.showMessageDialog(this,"Uspesno izvrsena izmena!");
            jcbAutobusi.removeAllItems();
            prepareIzmena();
        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this,"Sistem ne moze da zapamti autobus!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska pri izmeni autobusa!","Greska",JOptionPane.ERROR_MESSAGE);
            System.out.println(ex.getMessage());
        }
       
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void tbRegBrojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbRegBrojActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbRegBrojActionPerformed

    private void jcbAutobusiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAutobusiActionPerformed
       Autobus autobus = (Autobus)jcbAutobusi.getSelectedItem();
      if(autobus!=null){
       tbBrojMesta.setText(autobus.getBrojMesta()+"");
       tbGodProizvodnje.setText(autobus.getGodinaProizvodnje()+"");
       tbMarka.setText(autobus.getMarkaAutobusa());
       tbRegBroj.setText(autobus.getRegBrojVozila());
       tbVrsta.setText(autobus.getVrstaAutobusa().toString());
       tbBrojMesta.setEnabled(true);
      }
    }//GEN-LAST:event_jcbAutobusiActionPerformed

    private void jcbAutobusiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbAutobusiMouseClicked
       
       
    }//GEN-LAST:event_jcbAutobusiMouseClicked

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnIzmeni;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<Object> jcbAutobusi;
    private javax.swing.JLabel lblBrMesta;
    private javax.swing.JLabel lblGodinaProzivodnje;
    private javax.swing.JLabel lblMarka;
    private javax.swing.JLabel lblRegBroj;
    private javax.swing.JLabel lblRegBroj1;
    private javax.swing.JLabel lblVrsta;
    private javax.swing.JTextField tbBrojMesta;
    private javax.swing.JTextField tbGodProizvodnje;
    private javax.swing.JTextField tbMarka;
    private javax.swing.JTextField tbRegBroj;
    private javax.swing.JTextField tbVrsta;
    // End of variables declaration//GEN-END:variables

    private void prepareIzmena()  {
        try {
            List<Autobus> autobusi = Communication.getInstance().ucitajListuAutobusa();
   
            for (Autobus autobus : autobusi) {
                jcbAutobusi.addItem(autobus);
            }
            jcbAutobusi.setEnabled(true);
        } catch (Exception ex) {
            Logger.getLogger(FrmIzmeniAutobus.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
