/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package form;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import threads.DateTimeThread;

/**
 *
 * @author PC
 */
public class FrmMain extends javax.swing.JDialog {

    /**
     * Creates new form FrmMain
     * @param parent
     * @param modal
     */

    public FrmMain() {
        super(new JFrame(), true);
        initComponents();
        setTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDatePickerUtil1 = new org.jdatepicker.util.JDatePickerUtil();
        lblDatumVreme = new javax.swing.JLabel();
        lblDatumVremeText = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        tbMesto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JlMesta = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblDatumVreme.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblDatumVreme.setForeground(new java.awt.Color(0, 0, 0));
        lblDatumVreme.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDatumVreme.setText("datum i vreme");

        lblDatumVremeText.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblDatumVremeText.setForeground(new java.awt.Color(0, 0, 0));
        lblDatumVremeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDatumVremeText.setText("Datum :");

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("PRETRAZI VOZNJU");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tbMesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbMestoActionPerformed(evt);
            }
        });
        tbMesto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbMestoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbMestoKeyTyped(evt);
            }
        });

        JlMesta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JlMesta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlMestaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JlMesta);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("MESTO");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DATUM ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDatumVremeText, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDatumVreme, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(tbMesto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatumVreme, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDatumVremeText, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                            .addComponent(tbMesto)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(339, 339, 339))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbMestoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbMestoKeyTyped
        // TODO add your handling code here:
        
            
        
    }//GEN-LAST:event_tbMestoKeyTyped

    private void tbMestoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbMestoKeyReleased
        // TODO add your handling code here:
        DefaultListModel<String> listModel = new DefaultListModel<>();
        JlMesta.setModel(listModel);

        listModel.addElement("Beograd");
        listModel.addElement("Kragujevac");
        listModel.addElement("Knic");
        listModel.addElement("Lazarevac");
        listModel.addElement("Ljig");
        
        String prefix = tbMesto.getText().toLowerCase();
        List<String> filteredList = new ArrayList<>();

        // Filtriranje elemenata koji počinju na uneti prefiks
        for (int i = 0; i < listModel.getSize(); i++) {
            String element = listModel.getElementAt(i);
            if (element.toLowerCase().startsWith(prefix)) {
                filteredList.add(element);
            }
        }
        // Ažuriranje prikazane liste rezultata
        JlMesta.setListData(filteredList.toArray(new String[0]));
            
    }//GEN-LAST:event_tbMestoKeyReleased

    private void tbMestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbMestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbMestoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void JlMestaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlMestaMouseClicked
         String grad= String.valueOf(JlMesta.getSelectedValue());
         tbMesto.setText(grad);
    }//GEN-LAST:event_JlMestaMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> JlMesta;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDatumVreme;
    private javax.swing.JLabel lblDatumVremeText;
    private javax.swing.JTextField tbMesto;
    // End of variables declaration//GEN-END:variables

    private void setTime() {
        DateTimeThread dateTime= new DateTimeThread(lblDatumVreme);
        dateTime.start();
    }
}
