/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package form;

import communication.Communication;
import domain.Autobus;
import domain.Vozac;
import domain.VrstaAutobusa;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import tables.AutobusTableModel;

/**
 *
 * @author PC
 */
public class FrmPretaziAutobus extends javax.swing.JDialog {

    /**
     * Creates new form FrmPretaziAutobus
     */
    public FrmPretaziAutobus(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        prepareTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbTekst = new javax.swing.JLabel();
        lblRegBroj = new javax.swing.JLabel();
        tbRegBroj = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAutobusi = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pretrazi autobus"));

        jlbTekst.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbTekst.setText("Unesite registarski broj autobusa ili minimalan broj mesta koji Vam treba.");

        lblRegBroj.setText("Registarski broj: ");

        jTableAutobusi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableAutobusi);

        jButton1.setText("PRETRAZI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlbTekst)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblRegBroj, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tbRegBroj, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 106, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTekst)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegBroj)
                    .addComponent(tbRegBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       List<Autobus> autobusi = new ArrayList<>();
        if(tbRegBroj.getText().isEmpty()){
             JOptionPane.showMessageDialog(this, "Morate popuniti polje za registraciju!","Greska",JOptionPane.ERROR_MESSAGE);
             return;
        }
        Autobus autobus =  new Autobus(tbRegBroj.getText(),null,0,0,null);
        try {
            autobusi=Communication.getInstance().pretraziAutobus(autobus);
            if(autobusi==null|| autobusi.isEmpty()){
              JOptionPane.showMessageDialog(this, "Ne postoji auotbus sa zadatim registracionim brojem!","Greska",JOptionPane.ERROR_MESSAGE);
              return;
            }
            long i=1;
            TableModel model=new AutobusTableModel(autobusi);
            jTableAutobusi.setModel(model);
            jTableAutobusi.setVisible(true);

            
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        
      
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAutobusi;
    private javax.swing.JLabel jlbTekst;
    private javax.swing.JLabel lblRegBroj;
    private javax.swing.JTextField tbRegBroj;
    // End of variables declaration//GEN-END:variables

    private void prepareTable() {
        jTableAutobusi.setVisible(false);
        List<Autobus> autobusi = new ArrayList<>();
        TableModel model=new AutobusTableModel(autobusi);
         jTableAutobusi.setModel(model);
    }
}
